### PR TITLE
Relax xUnit3001 warning to allow for implicit constructors,

### LINKED ISSUE #1672: xUnit3001 warning - blech
I don't like this new analyzer. I thought it was a bug at first, but its apparently a feature.

"Classes that implement Xunit.Abstractions.IXunitSerializable must have a public parameterless constructor"

a) My classes do have an implicit public parameterless constructor. Why isn't that good enough?
b) https://xunit.github.io/xunit.analyzers/rules/xUnit3001 says to add an [Obsolete] attribute. I don't want to mark them as obsolete. I want to create instances of my test classes.

At least ignoring b) doesn't trigger another analyzer warning.

### PR DESCRIPTION
**Pull request by tiesmaster**
fixes [#1672](https://github.com/xunit/xunit/issues/1672).

### CODE REVIEW

**Comment by tiesmaster** [comment]
@marcind Do you have time take a look at this PR?

**Comment by tiesmaster** [comment]
@bradwilson Marcin hasn't been responsive. Do you maybe have some time to take a look at this PR?

**Comment by tiesmaster** [comment]
@bradwilson Any feedback on this?

**Review by marcind — APPROVED** [review]
Sorry for not looking at this earlier. Looks good.

**Comment by tiesmaster** [comment]
Thanks 🎉  I'm interested in doing some more contributions, but it demotivates if responsiveness is low. What is the best way to attract your attention? Twitter, Slack?

**Comment by tiesmaster** [comment]
To put the money where my mouth is ;) My next PR #110

**Comment by marcind** [comment]
Yeah, I totally get it when a repo owner is unresponsive. Been on the receiving side of that a number of times so I should know to behave better. But the truth is I have not been doing anything in the .Net world lately, so I can't promise I'll be 100% on top of it. I will endeavor to make an effort though.

**Comment by tiesmaster** [comment]
Yeah, I already thought that. I checked your profile back in April, and saw your activity in react or redux repos, so figured you made or expanded your skillset to frontend ;) I also took on learning react/redux/typescript a couple months ago for my team (where the new app eventually got put on ice), so I know how exhausting frontend can be 😕 

I'll keep my PRs small, and have patience ;)

**Pull request merged**
