### PR TITLE
Fixes xunit/xunit#2798: xUnit2007 code fix leads to CS8920 compiler error

### PR DESCRIPTION
**Pull request by etherfield**
Resolves #2798

### CODE REVIEW

**Comment by boerdereinar** [comment]
Does not work when adding extra abstraction layer:
```
public interface IInterface1 {
    public abstract void Method();
}

public interface IInterface2 : IInterface1 {
}
```

~~Also this is supported in .NET 7, but not as a preview in .NET 6.~~
Edit: Removed irrelevant info.

**Comment by bradwilson** [comment]
Thanks!

I assume the language preview features used here are all coming in C# 12? If so, then I'll just wait until C# 12 is released to add this. Should only be a few ~weeks~ days...

**Comment by bradwilson** [comment]
It appears this feature is not in C# 12, as it's still open: https://github.com/dotnet/csharplang/issues/4436

**Comment by boerdereinar** [comment]
@bradwilson This feature has already been introduced in C# 11, not C# 12. I have no idea why the proposal is still open. See https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/static-virtual-interface-members and https://github.com/dotnet/csharplang/blob/main/proposals/csharp-11.0/static-abstracts-in-interfaces.md

**Comment by bradwilson** [comment]
If you attempt to use it, you get told you must "enable preview features" which require attribute decoration of any affected type (or the assembly as a whole):

image

**Comment by bradwilson** [comment]
Note that this is with .NET SDK 8 and C# 12.

**Comment by bradwilson** [comment]
Maybe it's runtime-dependent?

**Comment by boerdereinar** [comment]
The target framework in that screenshot is .NET 6. You set it to at least .NET 7 in order for it to work.

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
