### PR TITLE
Fix InlineDataMustMatchTheoryParameters - support OptionalAttributes.

### PR DESCRIPTION
**Pull request by wachulski**
Adds support for System.Runtime.InteropServices.OptionalAttribute
in test method parameters.

Closes xunit/xunit#1638

### CODE REVIEW

**Comment by wachulski** [comment]
I'm wondering if we should start requiring documentation update for PRs touching rules. What do you think @marcind ? E.g. I wanted to update https://xunit.github.io/xunit.analyzers/rules/xUnit1009 but there is nothing there in place.

Any other plans/ideas to increase documentation coverage?

**Comment by wachulski** [comment]
Work needed: https://github.com/xunit/xunit/issues/1638#issuecomment-371084708 (Optionals came in 2.2)

**Review by marcind — APPROVED** [review]

**Comment by marcind** [comment]
Did not notice the comment about putting this behind a 2.2. version detect. If you could kindly submit a new PR.

**Comment by wachulski** [comment]
> Did not notice the comment about putting this behind a 2.2. version detect. If you could kindly submit a new PR.

Sure thing. I'm on it atm.

**Pull request merged**
