### PR TITLE
split collection size check analyzer into two

### PR DESCRIPTION
**Pull request by YevhenLukomskyi**
Resolves https://github.com/xunit/xunit/issues/1678

### CODE REVIEW

**Comment by YevhenLukomskyi** [comment]
@marcind can you please take a look at this one?

**Comment by marcind** [comment]
In the issue comments there's an [idea](https://github.com/xunit/xunit/issues/1678#issuecomment-395609499) to split the analyzer into two. Thoughts about doing that?

**Comment by YevhenLukomskyi** [comment]
This is a great idea, will update PR.

**Comment by YevhenLukomskyi** [comment]
@marcind any updates on this one?

**Comment by YevhenLukomskyi** [comment]
@marcind any plans on merging this PR?

**Comment by YevhenLukomskyi** [comment]
No activity for a long time. Closed as obsolete.

**Pull request closed without merging**
