### PR TITLE
Add CodeFixProvider to implement IClassFixture constructor

### LINKED ISSUE #2068: Add CodeFixProvider to implement IClassFixture constructor
# Summary
It would be nice if there was a code fix provider to generate the constructor and fields to access class fixture data. The documentation on IClassFixture states that 

```
To gain access to the fixture data from inside the test, a constructor argument should be added to the test class which exactly matches the TFixture.
```

```csharp
public class TestFixture
{
    public TestFixture()
    {
        // setup some test data to be made available in the test
    }
}

public class Test : IClassFixture<TestFixture>
{
    // theories and facts removed for brevity
}
```

When I add interface `IClassFixture<TestFixture>`  we could automatically transform the code like this:
```csharp
public class Test : IClassFixture<TestFixture>
{
    private readonly TestFixture _testFixture;
    public Test(TestFixture)
    {
        _testFixture = TestFixture;
    }
    // theories and facts removed for brevity
}
```
Would you accept a pull request implementing this kind of `codefixprovider`?

### PR DESCRIPTION
**Pull request by chinwobble**
closes https://github.com/xunit/xunit/issues/2068

### CODE REVIEW

**Comment by chinwobble** [comment]
yay build passed now

**Comment by chinwobble** [comment]
@bradwilson any idea when this can get merged?

Its something I would like to use personally when writing tests.

**Comment by chinwobble** [comment]
@marcind bump @bradwilson

**Comment by bradwilson** [comment]
Sorry, I have been unable to look at the actual code (beyond fixing the build break, which was obviously my fault) until today.

**Comment by bradwilson** [comment]
Thanks!

**Pull request merged**
