### PR TITLE
Update TestCaseMustBeLongLivedMarshalByRefObjectFixerTests.cs

### PR DESCRIPTION
**Pull request by IEvangelist**

### CODE REVIEW

**Comment by bradwilson** [comment]
Uhhh, no. 😛

**Comment by IEvangelist** [comment]
What?! C'mon now... this is a valid improvement. https://msdn.microsoft.com/en-us/magazine/dn818493.aspx, it is still an `async void`.

**Comment by bradwilson** [comment]
We support `async void`; in fact, I'll wager there are more `async void` unit tests in this code than `async Task`. There's zero reason to convert them.

**Comment by IEvangelist** [comment]
Just now saw that... interesting, thanks for enlightening me. :+1:

**Pull request closed without merging**
