### PR TITLE
Check whether first argument is an `int` in `AssertEqualShouldNotBeUsedForCollectionSizeCheck`

### PR DESCRIPTION
**Pull request by dougbu**
- xunit/xunit#1502

### CODE REVIEW

**Comment by jamesqo** [comment]
Could you please tests to verify that the fix works as intended? Thanks!

**Comment by dougbu** [comment]
@jamesqo will do&hellip;

**Comment by dougbu** [comment]
:up::date:

**Comment by marcind** [comment]
Thanks for the fix.

**Comment by marcind** [comment]
Thanks for the fix

**Pull request merged**
