### PR TITLE
Feat trigger x1010 when InlineData is negative int and parameter is uint

### PR DESCRIPTION
**Pull request by NormanFrieman**
When pass negative int in inlinedata and the parameter of test is uint, the test will fail in runtime

### CODE REVIEW

**Comment by NormanFrieman** [comment]
@dotnet-policy-service agree

**Comment by bradwilson** [comment]
Sorry for the delay, I thought I had already left a comment here but I must not have submitted it. ☹️ 

The fix provided here is very focused on specifically negative `int`s and `uint`s. An ideal fix would be generalized to support all integral types, ensuring compatibility.

**Comment by NormanFrieman** [comment]
@bradwilson I've improved the test I created that tests negative int to uint conversion scenarios. Are you suggesting that I include a fix for this issue as well? [issue 2983](https://github.com/xunit/xunit/issues/2983)

**Comment by bradwilson** [comment]
Thanks! I needed to fix some merge issues and wanted to add an edge case to the tests, but your branch is not open to pushes, so I had to do them myself. You're credited with the squashed commit: https://github.com/xunit/xunit.analyzers/commit/d25b3a43404a3ea0c11300b6cd0025accf2eebd8

**Pull request closed without merging**
